pipeline {
    agent { label 'window-01-node' }

    environment {
        APP_NAME = 'ecom-nextjs'
        DEPLOY_PATH = 'D:\\laptrinh\\jenskin-01-agent\\deploy_path\\ecom-nextjs'
        PROJECT_DIR = 'project-nextjs/ecom'
        PORT = '3000'
        NODE_ENV = 'production'
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    credentialsId: 'github-credential',
                    url: 'https://github.com/dochinhlatoi113/super-project.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                bat """
                    cd ${PROJECT_DIR}
                    npm install
                """
            }
        }

        stage('Build Next.js') {
            steps {
                bat """
                    cd ${PROJECT_DIR}
                    npm run build
                """
            }
        }

        stage('Create .env.production') {
            steps {
                bat """
                    cd ${PROJECT_DIR}
                    (
                      echo NODE_ENV=production
                      echo PORT=${PORT}
                    ) > .env.production
                """
            }
        }

        stage('Deploy Source Code') {
            steps {
                bat """
                    if exist "${DEPLOY_PATH}" rmdir /S /Q "${DEPLOY_PATH}"
                    mkdir "${DEPLOY_PATH}"

                    bat '''
                    robocopy project-nextjs/ecom "D:/laptrinh/jenskin-01-agent/deploy_path/ecom-nextjs" /E /MIR
                    exit 0
                    '''
                """
            }
        }

        stage('Start Application') {
            steps {
                bat """
                    pm2 delete ${APP_NAME} 2>nul

                    cd ${DEPLOY_PATH}
                    pm2 start npm --name ${APP_NAME} -- run start
                    pm2 save
                    pm2 list
                """
            }
        }

        stage('Health Check') {
            steps {
                bat """
                    timeout /t 5
                    curl http://localhost:${PORT}
                    pm2 info ${APP_NAME}
                """
            }
        }
    }

    post {
        success {
            echo '✅ DEPLOY SUCCESS'
        }
        failure {
            echo '❌ DEPLOY FAILED'
        }
    }
}
